export const TOGGLE_SONG_PLAY = 'TOGGLE_SONG_PLAY';
export const PLAY_A_SONG = 'PLAY_A_SONG';

export const UPDATE_VOLUME = 'UPDATE_VOLUME';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';

export const TOGGLE_LARGE_IMAGE_SONG_SIDEBAR =
  'TOGGLE_LARGE_IMAGE_SONG_SIDEBAR';
